version: 2

jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:8.0

    steps:
      - checkout
      - run:
          name: Test and publish coverage
          command: ./gradlew test jacocoTestReport coveralls

workflows:
  version: 2
  workflow:
    jobs:
      - build
